project:
  type: website
  output-dir: docs

website:
  title: "Aaron DiLorenzo | Research"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Thesis
        href: thesis.qmd
      - text: Oil & Gas Project
        href: fracking.qmd

format:
  html:
    theme: cosmo
    toc: false

