project:
  type: website
  output-dir: docs

website:
  title: "Aaron DiLorenzo"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Innovation Outcomes
        href: thesis.qmd
      - text: UOG & Induced Seismicity
        href: frackin.qmd
      - text: QXGBoost for NYC Construction Risk
        href: documents/qxgboost.pdf

format:
  html:
    theme: cosmo
    toc: false

